create table Drame(name varchar(30) NOT NULL,type varchar(10) NOT NULL,region int NOT NULL,director varchar(20),actor varchar(50),post varchar(100),introduction varchar(500),recommend varchar(10) NOT NULL, episode varchar(10) NOT NULL); 

insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('七日生','2','1','刘心刚','李晨','./posts/drame/qiRiSheng1.jpg,./posts/drame/qiRiSheng0.jpg','一次掩护邱永邦抽老千的行为，将李晓宇平静的生活打破。赌场老板被害，李晓宇被当成最大嫌犯逮捕，身为平面模特的女友文文在此时被霍雷兹帮的人贩子盯上绑走。一时无法脱身的李晓宇请邱永邦帮忙找回文文，却不知道，绑走文文的人正是邱永邦一伙。知道真相后的李晓宇以警察线人的身份追上邱永邦所在的华人旅游大巴，大巴已被邱永邦一伙...','0,1', '8');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('我只喜欢你','4','1','王之','吴倩','./posts/drame/woZhiXiHuanNi1.jpg,./posts/drame/woZhiXiHuanNi0.jpg','改编自乔一风靡全网的超人气小说《我不喜欢这世界，我只喜欢你》，源自作者真实经历的恋爱成长故事。 赵乔一和言默是高中同桌，一个是迷糊努力的偏科生，一个是外冷内热的超级学神，看似不对路的两人却情愫暗生。毕业前夕，言默表露心迹并跟乔一定下了一起出国读书的约定，乔一因家庭变故冷淡拒绝，二人陷入异国冷战，但对对方的思念...','0,1', '18');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('封神演义','1','1','吕行','王丽坤','./posts/drame/fengShenYanYi1.jpg,./posts/drame/fengShenYanYi0.jpg','殷商末年，纣王无道，荒淫度日，听信奸佞费仲谗言，欲将冀州侯苏护之女苏妲己占为己有，遂派大军压境，讨伐冀州以夺取妲己，不想妲己已被狐妖所附，丧失心智，助纣为虐。在妲己的煽动下，纣王杀文害武，斩妻杀子，聚敛民财，苦害生灵，与此同时，西伯侯姬昌勤于政事，善施仁德，西岐国力日渐强大。元始天尊见朝歌城已被妖孽所控，断定...','0,1', '33');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('一场遇见爱情的旅行','4','1','毛卫宁','陈晓','./posts/drame/yiChangYuJianAiQingDeLvXing3.jpg,./posts/drame/yiChangYuJianAiQingDeLvXing0.jpg','普通白领李心月以千万重金拍下大画家楚鸿飞的画作《宝贝》，这个奇怪的行为引起了警方的注意，被卧底警察金小天像影子一样追踪。俩人阴错阳差地一起上了楚鸿飞之子楚之翰的创业项目直播旅行房车，开往心月想念又害怕的故乡香格里拉。在风景如画的旅途中，李心月与一直保护她的金小天互生好感，但金小天碍于卧底的身份一直不能表白。为...','0,3', '33');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('如果可以这样爱','4','1','王类','刘诗诗','./posts/drame/ruGuoKeYiZheYangAi4.jpg,./posts/drame/ruGuoKeYiZheYangAi0.jpg','一对已婚男女突然徇情自杀，以为可以结束这一切，却不料悲剧才刚刚开始——他们的爱人，耿墨池和白考儿，同时在葬礼上邂逅。面对同样的背叛他们同时选择报复但又同时爱上彼此，注定饱受打击和折磨。然而他们想真心拥有彼此时，老天已不给他们机会，耿墨池身患不治之症注定要离去，而这时候白考儿亡夫的哥哥祁树礼出现了，纠结在两个男...
','0,4', '42');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('青春斗','4','1','赵宝刚','郑爽','./posts/drame/qingChunDou1.jpg','青春是什么，青春是可以肆意挥霍时间和精力，是在长大成人的痛苦中的纠结和徘徊、是在一段段破碎的爱情和友情的道路上潇洒前行。普通的年轻人如何从学校大学毕业生成为社会中坚力量，其中的历程痛苦而漫长。他们要逼迫自己成长，要斗争，要自我审视和沉淀，成长的阵痛是激励自己前行的苦口良药。因为时代的高速发展，90后年轻人的青...','1', '38');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('仙剑客栈','3','1','探花','吴磊','./posts/drame/xianJianKeZhan1.jpg','《仙剑客栈》是纪念仙剑系列20年推出的首部跨次元互动网剧，该剧由“仙剑之父”姚壮宪亲自监制，融合历代仙剑游戏的剧情构架，浓缩成大团圆式平行世界，打破时空限制，让所有一切回到仙剑故事开始的地方——余杭镇仙剑客栈。历代仙剑游戏中的知名角色都将在剧中汇聚，改写仙剑故事的悲情结局，重塑一个欢乐的《仙剑客栈》。90后小...','1', '30');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('知否知否应是绿肥红瘦','1','1','张开宙','赵丽颖','./posts/drame/zhiFouZhiFouYingShiLvFeiHongShou2.jpg','盛家六姑娘盛明兰从小聪颖貌美，却遭遇嫡母不慈，姐妹难缠，父亲不重视，生母被害去世的困境。她藏起聪慧，掩埋锋芒，忍辱负重在逆境成长，在万般打压之下依然自立自强，终历尽艰难为母报仇。在这一过程中，盛明兰结识了宁远侯府二公子顾廷烨。顾廷烨帮过盛明兰，也刻薄地对待过盛明兰，他见过盛明兰软弱表皮下的聪慧锐利，也见过她刚... ','2', '78');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('镇魂','2','1','周远舟','朱一龙','./posts/drame/zhenHun2.jpg','本剧改编自晋江大神级作家Priest同名小说。万年前，为了抢夺海星的生存资源，地星人中的极端分子大举进攻整个海星，引发了海星人和地星人的史前大战。为了与拥有异能的地星人抗衡，海星人打造了四件圣器，并在领袖“昆仑”和地星和平派领袖黑袍使的带领下，“海星正义联盟”最终取得了大战的胜利，地星人退回到地核中生活。大战...','2', '40');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('虎啸龙吟','5','1','张永新','于和伟','./posts/drame/huXiaoLongYin2.jpg','该剧延续了《大军师司马懿之军师联盟》的精彩剧情，从司马懿戎装佩剑意气风发，到诸葛亮手持白鹤羽扇挥斥方遒，开启了新的一场场后三国精彩对战。昼夜兼程征孟达、空城计、高平陵事件，以及司马懿与第二代魏帝曹叡的关系都将在剧中娓娓道来。司马懿的身份会变为“托孤重臣”，进一步走入曹叡、曹芳时代的政治权利中枢，并遇到人生中最...','2', '44');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('美女的诞生','6','3','李昌明','韩艺瑟','./posts/drame/meiNvDeDanSheng2.jpg','该剧讲述了一个通过整容与减肥来转变人生的女人和这个将她改造成美女的男人之间的浪漫爱情故事。韩泰熙是财阀SJ集团的得力继承者，因为心理受到冲击患上“心碎综合症”，他的性格犹如活火山般难以预测，是一个水火不兼容的角色，为了寻找回自己心爱的女人，他将肥胖女人莎金兰改造成了漂亮无比的莎拉，接着在与这个由自己改造的女人...','2', '21');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('神盾局特工','8','2','乔斯.韦登','克拉克·格雷格','./posts/drame/shenDunJuTeGong2.jpg','神盾局特工菲尔·科尔森从纽约大战归来，回到执法机构神盾局。他组织了一支精锐、训练有素的特工小组，处理那些还未被指定为机密的案件，那些新的、陌生的、未知的东西。这个小组包括正直坦率的沃德探员，他是位作战和间谍活动的专家，梅探员是位飞行员及武术专家，菲兹探员是一位科学家，不过他在人际交往的能力则略显尴尬，西蒙斯探...','2', '22');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('颤抖吧，阿部','8','1','赵小溪','安悦溪','./posts/drame/chanDouBaABu3.jpg','朵星少女阿部察察意外降落地球，寄生在地球人唐青叶的身上，与大唐杰出青年才俊唐青风相遇，人生轨迹从此发生惊天逆转。这对欢喜冤家不光卷入了皇室纷争，还意外被星际海盗当作了攻击目标……','3', '25');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('情满四合院','7','1','刘家成','何冰','./posts/drame/qingManSiHeYuan3.jpg','本剧讲述了从上世纪六十年代到九十年代发生在北京四合院里的故事。何雨柱是钢厂食堂的厨师，为人善良仗义却口无遮拦，人称“傻柱”。同院住着钢厂工人秦淮茹，她讲孝道，又能干，膝下有一儿两女，但丈夫因工伤去世，日子过得比较艰难。院里住着钢厂放映员许大茂，为人自私自利，跟傻柱是对头。院里还住着三位受人尊敬的老工人，人称“...','3', '46');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('楚汉传奇','5','1','高希希','陈道明','./posts/drame/chuHanChuanQi3.jpg','秦始皇猝死，奸臣弄权，二世继位，残暴不仁，滥征民力，民不聊生，流寇四起。恰此风云际会之际，英雄豪杰、蜂起八荒，纷纷下海造反，群相逐鹿中原。一时间机诡百出，动人心弦的谋略战争竞相展现，英雄难过美人关，霸王、虞姬、刘邦、吕后，上演缠绵悱恻的传奇爱情。','3', '80');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('天龙八部','3','1','周晓文','胡军','./posts/drame/tianLongBaBu3.jpg','乔峰追寻身世时屡遭奸人所害，含冤莫白，更错杀红颜知己阿朱，后又为救阿朱之妹阿紫而寻医至大辽国，辗转成为大辽国的南院大王。但其与中原武林的关系则更趋恶劣，并在聚贤庄一役中与不少英雄侠士决裂。段誉之父是风流潇洒、处处留情的大理镇南王段正淳，而段誉也继承了父亲多情的性格，但他为人豁达开朗，对貌若天仙的王语嫣...','3', '40');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('白夜追凶','2','1','王伟','潘粤明','./posts/drame/baiYeZhuiXiong4.jpg','一场灭门惨案，让原本逍遥浪荡的关宏宇成了在逃的通缉嫌犯。身为刑侦支队队长的双胞胎哥哥关宏峰，誓要查出真相，但出于亲属回避的原则，警队禁止关宏峰参与灭门案的调查工作，关宏峰义愤辞职。调任了代支队长的周巡处于破案压力，也为了追寻关宏宇的下落，他设计让离职的关宏峰以“编外顾问”的身份继续参与各大重案要案的调查，而警...
','4', '32');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('甄嬛传','1','1','郑晓龙','孙俪','./posts/drame/zhenHuanZhuan4.jpg','时为满清雍正元年，结束了血腥的夺位之政，国泰民安，政治清明，但在一片祥和的表象之下，一股暗流蠢蠢欲动。后宫之中，华妃与皇后分庭抗礼，各方势力裹挟其中，凶险异常。在太后的主持下，一场盛大的选秀拉开帷幕。以此为机缘，美丽善良的女孩——大理寺少卿甄远道长女甄嬛意外得到皇帝的赏识，从此步入皇宫。在皇后和华妃两方势力的...
','4', '76');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('青云志','3','1','周远舟','赵丽颖','./posts/drame/qingYunZhi4.jpg','草庙村少年张小凡，在经历全村尽灭的惨案后，被青云门收归门下。为报答师门恩情，张小凡勤学苦练，却因自身愚钝，一无所成。陷入迷茫与孤独境遇中的他，幸有鬼王之女碧瑶和好友林惊羽从旁安慰陪伴，度过了人生最彷徨的阶段，于是三人一同修行，一同成长。在经历过一次次的坎坷磨难后，张小凡逐渐成熟，而与碧瑶的感情，也在患难与共中...
','4', '58');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('三国演义','5','1','张中一','唐国强','./posts/drame/sanGuoYanYi4.jpg','东汉末年，山河动荡，刘汉王朝气数将尽。内有十常侍颠倒黑白，祸乱朝纲。外有张氏兄弟高呼“苍天已死，黄巾当立”的口号，掀起浩大的农民起义。一时间狼烟四起，刘家朝廷宛如大厦将倾，岌岌可危。 　　正所谓乱世出英雄，曹操（鲍国安 饰）、公孙瓒、袁术、袁绍、吕布（张光北 饰）、刘备、孙策、关羽、张飞、诸葛亮（唐国强 饰）...
','4', '84');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('小丈夫','6','1','姚晓峰','余飞鸿','./posts/drame/xiaoZhangFu5.jpg','姚澜年近三十三，终于迎来自己的婚礼，却突然遭遇新郎田坤的前女友抢婚，气的她取消婚礼愤然离开。谁知这桩闹事竟意外促成了姚澜和大男孩陆小贝的不解之缘。虽然他们年龄相差八岁，但是陆小贝充满活力和浪漫，姚澜拥有成熟与稳重，这使得两人深深地互相吸引。不过理智告诉姚澜不能沉溺于这种盲目的激情，现实中姐弟恋的诸多问题也接二...','5', '43');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('爱上查美乐','6','1','柯瀚辰','王心凌','./posts/drame/aiShangZhaMeiLe5.jpg','风靡全亚洲的音乐才子韩以烈(贺军翔饰演)是某卫视知名综艺节目的评委，他性格怪异，作风霸道，经常让暗恋他的经纪人楚少茵(柳岩饰演)为其收拾烂摊子。査美乐(王心凌饰演)是一个坚强善良的平凡女孩，她相信只要努力付出就有回报。为实现男友韩以风的梦想，她放弃自己的事业开了一家面包店。美乐阴差阳错之下与冷酷霸道...','5', '25');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('秘密花园','8','1','申宇哲','玄斌','./posts/drame/miMiHuaYuan5.jpg','百货公司社长金周元帅气多金高学历，信奉不浪费时间和感情的政治婚姻。他的表哥是大受女性欢迎的韩流明星奥斯卡，为了帮奥斯卡摆平绯闻，金周元来到电影拍摄现场，却误打误撞地带走了特技替身演员吉罗琳。很快，留着一头帅气短发、行动干脆利落的吉罗琳俘虏了金周元的心，然而二人之间经济水平以及阶级地位的巨大差异，让金社长内心十...','5', '20');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('一千零一夜','8','1','金沙','迪丽热巴','./posts/drame/yiQianLingYiYe5.jpg','花艺公司职员凌凌七是一个真诚善良、乐于助人的好姑娘，但是性格上却很自卑懦弱。这个缺点严重地影响了她的生活，使她在工作上难以展开拳脚、实现理想，同时也不敢向爱慕的同事柏海表达情感。一次意外的机会，她和柏海参加了好梦科技公司推出的改善睡眠的高科技手环测试。手环中功能磁共振仪器发生故障，误将凌凌七的脑电波数据传输到...','5', '49');
insert into Drame(name,type,region,director,actor,post,introduction,recommend, episode) values('最动听的事','4','1','徐赫灿','赵露思、王以纶','./posts/drame/zuiDongTingDeShi5.jpg','出身普通家庭，热爱配音的女孩贝耳朵，一直怀抱着去日本留学成为一名专业配音员的梦想，但母亲却希望她在最有资本的年龄嫁给富人，为此不断安排相亲，让贝耳朵疲于应对。为了凑齐留学的费用，也为了帮闺蜜唐栗救急，贝耳朵无奈之下加入了一档情侣真人秀的节目，在节目中偶遇了家世显赫的世界顶级小提琴制琴师叶抒微。叶抒微出身艺术世...','5', '24');

