 create table Film(name varchar(30) NOT NULL,type varchar(10) NOT NULL,region int NOT NULL,director varchar(20),actor varchar(50),post varchar(200),introduction varchar(500),recommend varchar(10) NOT NULL);

insert into Film(name,type,region,director,actor,post,introduction,recommend) values('大圣归来','6','1','田晓鹏','张磊','./films/daShengGuiLai.jpg','五百年前，由石猴变化而成的齐天大圣孙悟空（张磊 配音）大闹天宫，最终被如来佛祖镇压在了五行山下。此去经年，长安城内突然遭到山妖洗劫，童男童女哭声连连，命悬一线。危机时刻，自幼被行脚僧法明（吴文伦 配音）抚养长大的江流儿（林子杰 配音）救下了一个小女孩，结果反遭山妖追杀。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('大鱼海棠','6','1','梁旋','季冠霖','./films/daYuHaiTang.jpg','所有活着的人类，都是海里一条巨大的鱼，出生的时候他们从海的此岸出发。他们的生命就像横越大海，有时相遇，有时分开……死的时候，他们便到了岸，各去各的世界。四十五亿年前，这个星球上，只有一片汪洋大海，和一群古老的大鱼。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('爱宠大机密','6','2','克里斯.雷纳德','路易斯.CK','./recommend/aiChongDaJiMi.jpg','位于纽约的一栋红色公寓中，狗狗Max（路易·CK 配音）陪伴它的主人Katie（艾丽·坎伯尔 配音）过着平凡而幸福的生活。它不明白主人为什么每天早出晚归，总希望Katie能时时刻刻陪伴着它。这天傍晚，主人带回了一条身形庞大的狗狗Duke（艾瑞克·斯通斯崔特 配音），顿时让麦克感觉如天塌了一般。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('疯狂动物城','6','2','里奇.摩尔','金妮弗.古德温','./recommend/fengKuangDongWuCheng.jpg','故事发生在一个所有哺乳类动物和谐共存的美好世界中，兔子朱迪（金妮弗·古德温 配音）从小就梦想着能够成为一名惩恶扬善的刑警，凭借着智慧和努力，朱迪成功的从警校中毕业进入了疯狂动物城警察局，殊不知这里是大型肉食类动物的领地，作为第一只，也是唯一的小型食草类动物，朱迪会遇到怎样的故事呢？','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('头脑特工队','6','2','彼特.道格特','黛安.琳恩','./films/touNaoTeGongDui.jpg','可爱的小女孩莱莉（凯特林·迪亚斯 配音）出生在明尼苏达州一个平凡的家庭中，从小她在父母的呵护下长大，脑海中保存着无数美好甜蜜的回忆。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('白蛇：缘起','6','1','黄家康','杨天翔','./recommend/baiSheYuanQi.jpg','失忆少女小白被捕蛇人阿宣所救，为了解开自己的身份谜团，小白在阿宣的帮助下开始寻找线索。两人历经艰难险阻，年少男女在一路冒险中萌生爱慕之情。同时，小白的蛇妖身份也逐渐揭开，一场围绕人与妖的纠葛爱情故事随之展开。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('朝花夕誓','6','3','OkadaMari','石见舞菜香','./films/zhaoHuaXiShi.jpg','远离尘嚣的世外桃源，居住着被称为“离别一族”的伊奥鲁夫人。他们出生之后，长到15岁左右便不再生长，即使活过数百年也始终保持着少男少女的模样。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('你的名字','6','3','新海诚','神木隆之介','./films/niDeMingZi.jpg','在远离大都会的小山村，住着巫女世家出身的高中女孩宫水三叶（上白石萌音 配音）。校园和家庭的原因本就让她充满烦恼，而近一段时间发生的奇怪事件，又让三叶摸不清头脑。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('烟花','6','3','新房昭之','宫野真守','./recommend/yanHua.jpg','故事发生在某个海滨城市，炎热的暑假到来，无论大人还是孩子都满心期待着不久即将举行的烟火大会。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('猫与桃花源','6','1','王微','张喆','./recommend/maoYuTaoHuaYuan.jpg','一只常常在窗台发呆的家猫毯子，一直以来和儿子斗篷安逸地生活在城市的一座高楼公寓中。有一天充满好奇心的斗篷离开了家，想去看看外面的世界，去寻找传说中的属于猫的桃花源。','99');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('海洋奇缘','6','1','约翰.马斯克','道恩.强森','./films/haiYangQiYuan.jpg','故事最早始于住在风和海的半神毛伊（道恩·强森 配音），他偷走了女神的特菲堤之心，导致岩浆魔鬼厄卡陷入疯狂的状态，南太平洋各小岛也面临着毁灭的威胁。','99');

insert into Film(name,type,region,director,actor,post,introduction,recommend) values('流浪地球','8','1','郭帆','吴京,李光洁','./films/liuLangDiQiu.jpg,./films/liuLangDiQiu1.jpg','太阳即将毁灭，人类在地球表面建造出巨大的推进器，寻找新家园。然而宇宙之路危机四伏，为了拯救地球，为了人类能在漫长的2500年后抵达新的家园，流浪地球时代的年轻人挺身而出，展开争分夺秒的生死之战。','0,1,2');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('人间喜剧','3','1','孙周','艾伦,任达华','./films/renJianXiJu.jpg,./films/renJianXiJu1.jpg','电影 《人间·喜剧》 讲述了又怂又没出息的电台主播濮通，交不起房租讨不回薪水，媳妇都要闹离婚。莫名被卷进一场阴谋漩涡，怂人濮通一夜逆袭，拳打黑帮大佬，绑架首富独子，各路奇葩依次登场，濮通的喜剧人生由此爆笑展开……','0,1');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('狂暴凶狮','7','2','迪克.麦斯','艾比.霍尔斯','./films/kuangBaoXiongShi.jpg,./recommend/kuangBaoXiongShi1.jpg','在阿姆斯特丹，警方发现了被残忍杀害的一家人的尸体，警方对此案一时之间毫无头绪。但是阿姆斯特丹动物园的兽医Lizzie通过伤口怀疑这应该是一只大型的狮子所为。','0,7');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('阳台上','5','1','张猛','周冬雨,王锵','./films/yangTaiShang.jpg,./films/yangTaiShang1.jpg','《阳台上》讲述了一个关于“复仇”的故事。整日无所事事的张英雄（王锵 饰）一直生活在父母的溺爱下。父亲因为与拆迁工作人员陆志强发生冲突而忽然离世，张英雄决定要为父亲报仇。','0');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('傀儡姬','5','1','侯国涛','张冬,季晨','./films/kuiLeiJi.jpg,./films/kuiLeiJi1.jpg','太鬼马女偃师师师为寻找师兄勇闯城主府，却将城主姬夜辰错认成大护卫。二人被卷入数起怪异事件，渐生情愫，师师却发现对方不但是傀儡人，而且可能是杀死飞赫的凶手。','0,1');

insert into Film(name,type,region,director,actor,post,introduction,recommend) values('风中有朵雨做的云','5','1','娄烨','马思纯,井柏然,宋佳','./films/fengZhongYouDuoYuZuoDeYun.jpg','沿海小城，年轻警官杨家栋初来乍到，恰遇建委主任唐奕杰坠楼身亡。杨家栋展开调查，惨遭革职、追杀，一路逃亡香港，与死者女儿小诺意外邂逅，在小诺的协助下继续调查，浑然不觉自己正落入一个纯情陷阱……','1,2');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('绿皮书','3','2','彼得.法拉利','维果.莫腾森','./films/lvPiShu.jpg','真实故事改编，聚焦意裔美国人Tony Lip，他是一个受过七年级教育的保镖。1962年被聘用为世界上最好的爵士钢琴家Dr. Don Shirley开车，后者从纽约开始举办巡回演奏，深入前民权运动时期的南方腹地。','1,3');

insert into Film(name,type,region,director,actor,post,introduction,recommend) values('飞驰人生','3,4','1','韩寒','沈腾','./films/feiChiRenSheng.jpg','曾经在赛车界叱咤风云、如今却只能经营炒饭大排档的赛车手张驰决定重返车坛，在职业生涯的尾声挑战年轻一代的天才，他想聚齐昔日的搭档们，召唤神龙，再现光辉岁月，不料却遭现实狠狠打脸，状况百出。','2');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('盗浪淘沙','4','1','罗乐','吴千语','./films/daoLangTaoSha.jpg','讲述了少年无妄、狗子和明珠心怀正义，为保护苍生和奸臣刘霸山斗智斗勇的故事。故事的男主角无妄和好友狗子依靠倒斗生存。意外接到刘霸山的单子，帮他寻找玉玦以及邪帝之墓，获取长生晶石。','2');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('万妖国','1','1','柳航','吴孟达','./films/WanYaoGuo.jpg','自幼跟随师傅严崇礼修习方术的混元山方士张文才，一直跟随师傅在人间除妖降魔，一日，张文才在皇宫中给国王表演方术时，偶然中发现了有小妖在皇宫内作祟，原来皇宫内时常有人被小妖附体为非作歹，国师级方士陆离作为国师首当其冲与黑袍白袍做法降妖','2');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('复仇者联盟3','4,8','2','安东尼.罗素','小罗伯特.唐尼','./films/fuChouZheLianMeng3.jpg','最先与灭霸军团遭遇的雷神索尔一行遭到惨烈打击，洛基遇害，空间宝石落入灭霸之手。未几，灭霸的先锋部队杀至地球，一番缠斗后掳走奇异博士。为阻止时间宝石落入敌手，斯塔克和蜘蛛侠闯入了敌人的飞船。','3');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('复仇者联盟','4,8','2','安东尼.罗素','小罗伯特.唐尼','./films/fuChouZheLianMeng.jpg','最先与灭霸军团遭遇的雷神索尔一行遭到惨烈打击，洛基遇害，空间宝石落入灭霸之手。未几，灭霸的先锋部队杀至地球，一番缠斗后掳走奇异博士。为阻止时间宝石落入敌手，斯塔克和蜘蛛侠闯入了敌人的飞船。','3');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('密室逃生','2,7','2','亚当.罗比特尔','泰勒.拉塞尔','./films/miShiTaoSheng.jpg','六位身份各异的人因一个神秘包裹而聚集迷宫密室，他们被通知倘若顺利走出迷宫密室，赢家将会获得百万美元的奖励。然而就在游戏开局之后，他们却意外发现自己陷入了惊天阴谋，如果不及时找到线索解谜，他们便会悲惨死去','3');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('速度与激情8','4,7','2','加里.格雷','道恩.强森','./films/suDuYuJiQing8.jpg','《速度与激情8》是《速度与激情》系列电影的第八部，是由美国环球影业发行，由F·加里·格雷执导，范·迪塞尔、道恩·强森、杰森·斯坦森、查理兹·塞隆联合主演。','3');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('无双','4','1','庄文强','周润发','./films/wuShuang.jpg','《无双》讲述了以代号“画家”（周润发 饰）为首的犯罪团伙，掌握了制造伪钞技术，难辨真伪，并在全球进行交易获取利益，引起警方高度重视。','4');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('精武英雄','4','1','陈嘉上','李连杰','./films/jingWuYingXiong.jpg','李连杰在片中扮演的陈真成了留日学生，而且喜欢上日本女孩渡边光孝。因为师父霍元甲之死，陈真回到中国，协助师父之子霍廷恩主持精武门的业务，不料却引起了他的妒忌，师兄弟之间引发权力之争。','4');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('追龙','4','1','王晶','刘德华','./films/zhuiLong.jpg','电影讲述了香港现代史上两大著名狠角色大毒枭跛豪（甄子丹 饰）、五亿探长雷洛（刘德华 饰）的传奇故事。上世纪六七十年代，香港由英国殖民，权势腐败、社会混乱。','4');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('方世玉','3,4','1','元奎','李连杰','./films/fangShiYu.jpg','该片讲述了方世玉不知道他父亲是红花会的成员。一次，他父亲为了保护红花会的花名册不落入官府的手中而被捕。为了救他父亲，方世玉独闯刑场。','4');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('功夫','3,4','1','周星驰','周星驰','./films/gongFu.jpg','1940年代的上海，自小受尽欺辱的街头混混阿星（周星驰 饰）为了能出人头地，可谓窥见机会的缝隙就往里钻，这次他盯上行动日益猖獗的黑道势力“斧头帮”，想借之大名成就大业。','4');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('美人鱼','5','1','周星驰','邓超','./films/meiRenYu.jpg','白手起家的富豪刘轩（邓超 饰）新拍下了一块地皮，并联合了女强人李若兰（张雨绮 饰）使用恐怖的声呐技术驱赶鱼类，以便日后填海造地。','5');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('澳门风云3','3,4','1','王晶','刘德华','./films/aoMenFengYun3.jpg','石一坚（周润发 饰）在女儿阿彩（童菲 饰）的婚礼上，因误用兄弟小马（张家辉 饰）的“催眠治疗”加上机器人炸弹袭击而变得精神错乱。','5');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('西游伏妖篇','3,4','1','徐克','吴亦凡','./films/xiYouFuYaoPian.jpg','本片作为《西游降魔篇》的后续故事讲述了唐三藏（吴亦凡 饰）在上集感化了杀死段小姐的齐天大圣，并且收其为徒之后，带着孙悟空（林更新 饰）、猪八戒（杨一威 饰）及沙僧（巴特尔 饰）一行四人踏上了西天取经之旅。','5');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('红海行动','4','1','林超贤','黄景瑜','./films/hongHaiXingDong.jpg','索马里海域外，中国商船遭遇劫持，船员全数沦为阶下囚。蛟龙突击队沉着应对，潜入商船进行突袭，成功解救全部人质。返航途中，非洲北部伊维亚共和国发生政变，恐怖组织连同叛军攻入首都，当地华侨面临危险，海军战舰接到上级命令改变航向，前往执行撤侨任务。','5');
insert into Film(name,type,region,director,actor,post,introduction,recommend) values('智取威虎山','4','1','徐克','梁家辉','./films/zhiQuWeiHuShang.jpg','1947年冬，为了从土匪手中夺取控制东北九岭上万先遣军的分布图，东北民主联军203小分队队长少剑波（林更新 饰）委派侦查员杨子荣（张涵予 饰）卧底潜入最大的土匪山头“威虎山”。','5');

