create table VarietyShow(name varchar(30) NOT NULL,type varchar(15) NOT NULL,episodes varchar(10) NOT NULL,region int NOT NULL,director varchar(20),actor varchar(50),post varchar(200),introduction varchar(500),recommend varchar(10) NOT NULL);

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('高能少年团2','1','36','1','丁卿','王俊凯/董子健/杨紫','./varietyshow/GAONENGSHAONIANTUAN2.jpg,./varietyshow/GAONENGSHAONIANTUANDAHAIBAO.jpg','《高能少年团》是浙江卫视的一档室内加户外多场景式的偶像对抗挑战类真人秀。节目以明星真人秀的形式记录每个少年的高能挑战，意想不到的对手、青春奇幻的互动、绝不能输的挑战，力争展现出少年们的朝气蓬勃。第二季将以“一首歌、一座城”为线索，让高能少年们在不同城市的风土人情中体味冒险与成长。','0,1');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('极限挑战3','1','24','1','严敏','黄渤/孙红雷/罗志祥','./recommend/JIXIANTIAOZHAN3.jpg','《极限挑战》是东方卫视打造的一档大型原创励志星素互动综艺节目。本季黄渤、孙红雷、黄磊、罗志祥、王迅、张艺兴组成的“极限男人帮”原班人马再度登场，将继续延续以往正能量理念，与普通百姓“亲密接触”，深入民众当中体验各种职业，寻找“唤醒城市的人”。','1,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('极限挑战4','1','24','1','严敏','黄渤/孙红雷/罗志祥','./varietyshow/JIXIANTIAOZHAN4.jpg,./recommend/JIXIANTIAOZHANDAHAIBAO.jpg','《极限挑战》是东方卫视打造的一档大型原创励志星素互动综艺节目。第四季以“向美好生活，出发”为主题，描绘各行各业的“奋斗”姿态，向新时代致敬。第四季节目将有各行各业的精英强势加入，以更强的星素互动拉近与观众之间的距离，让路人的参与感更强，同时通过强化素人经历，传递出积极向上的奋斗力量，进一步强化“亲民暖综”的定位，带给观众更多的陪伴意义以及更强的亲切感和认同感。','0,7');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('这就是灌篮1','1','24','1','朱玲','周杰伦/易建联/李易峰','./varietyshow/ZHEJIUSHIGUANLAN1.jpg','《这就是灌篮》是一档由优酷&浙江卫视联合播出的中国首档大型青春篮球竞技原创节目。周杰伦&林书豪、李易峰&郭艾伦分别担任两大篮球阵营领队，集结热爱篮球的年轻人，引领全民篮球狂潮。四位领队，两支战队，上演最燃3V3篮球对战。用最真实的逐梦之路，唤醒青春热血。','1,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('奔跑吧兄弟1','1','15','1','陆皓','邓超/angelababy/李晨','./varietyshow/BENPAOBAXIONGDI1.jpg','《奔跑吧兄弟》是浙江卫视推出的一档新的大型户外真人秀节目。节目原型为韩国超人气综艺节目《Running Man》。浙江卫视还将携手韩国SBS电视台的原班制作团队，并邀请中国国内知名综艺节目团队，打造继《中国好声音》之后浙江卫视娱乐节目的又一大标杆。','3');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('奔跑吧兄弟2','1','12','1','陆皓','邓超/angelababy/李晨','./varietyshow/BENPAOBAXIONGDI2.jpg','《奔跑吧兄弟》是浙江卫视推出的一档新的大型户外真人秀节目。节目原型为韩国超人气综艺节目《Running Man》。浙江卫视还将携手韩国SBS电视台的原班制作团队，并邀请中国国内知名综艺节目团队，打造继《中国好声音》之后浙江卫视娱乐节目的又一大标杆。','3');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('奔跑吧兄弟3','1','12','1','陆皓','邓超/angelababy/李晨','./varietyshow/BENPAOBAXIONGDI3.jpg,./varietyshow/BENPAOBAXIONGDIDAHAIBAO.jpg','《奔跑吧兄弟》是浙江卫视推出的一档新的大型户外真人秀节目。节目原型为韩国超人气综艺节目《Running Man》。浙江卫视还将携手韩国SBS电视台的原班制作团队，并邀请中国国内知名综艺节目团队，打造继《中国好声音》之后浙江卫视娱乐节目的又一大标杆。','0,3');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('中国好声音2018','2','13','1','金磊','周杰伦/谢霆锋/李健/庾澄庆','./recommend/ZHONGGUOHAOSHENGYIN2018.jpg','《中国好声音》是由浙江卫视和灿星制作联手打造的音乐励志评论类节目。节目旨在为中国乐坛的发展提供一批怀揣梦想、具有天赋才华的音乐人。周杰伦、庾澄庆、谢霆锋、李健四位导师通过盲选选择自己心仪的学员组成战队，并一路带领自己的战队学员力争赢得冠军。','99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('这就是街舞1','2','12','1','陆伟','易烊千玺/罗志祥','./varietyshow/ZHEJIUSHIJIEWU.jpg','《这！就是街舞第一季》是由优酷、天猫、微博、巨匠出品，联手灿星制作的街舞选拔类真人秀，共十二期，由易烊千玺、罗志祥、韩庚、黄子韬担任明星队长。','1,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('热血街舞团','2','13','1','车澈','鹿晗/陈伟霆/王嘉尔','./recommend/REXUEJIEWUTUAN2018.jpg','《热血街舞团》是由《中国有嘻哈》原班人马倾力打造一档自制综艺节目，总监制爱奇艺高级副总裁陈伟，总导演车澈，音乐总监刘洲，于2018年3月17日在爱奇艺首播上线。','1,2,99');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('完美的餐厅','1,3','13','1','林芯翼','薛凯琪/王菊/陈立农/黄明昊','./recommend/WANMEIDECANTING.jpg','《完美的餐厅》是由兴格传媒、优酷平台、口碑app共同打造的节目。节目视线聚焦于青年人的创业生活。','2,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('锋味2018','1,3','12','1','高伟恩','谢霆锋','./varietyshow/FENGWEI2018.jpg','《锋味2018》是一档大型生活类户外美食节目。谢霆锋邀请多位明星好友，共同前往希腊米克诺斯岛、捷克布拉格、俄罗斯圣彼得堡、土耳其伊斯坦布尔、成都、厦门等国内外著名美食旅游都市，品尝各种特色美食，体验各地独特的风土人情与当地人的生活方式。每一集还将走近一位当地人的日常生活，并在他家的厨房内，为他量身打造一道专属的“锋味”，讲述“料理与人”之间的精彩故事。','99');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('花儿与少年1','1,4','8','1','廖珂','刘涛/许晴/张翰','./varietyshow/HUAERYUSHAONIAN1.jpg','《花儿与少年第一季》是湖南卫视推出的大型明星姐弟自助远行真人秀节目，节目共8期。第一季节目七位固定成员是郑佩佩、张凯丽、许晴、刘涛、李菲儿、张翰、华晨宇。节目中两位“少年”带领五位“姐姐”，开启一段为期十五天从意大利到西班牙的没有经纪人、不准带助理、每天生活费有限的限制下，在人生地不熟，甚至语言都根本不通的国度，完成一段异域的背包奇妙之旅。','99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('花儿与少年2','1,4','11','1','廖珂','许晴/宁静/杨洋','./varietyshow/HUAERYUSHAONIAN2.jpg','《花儿与少年第二季》是湖南卫视推出的大型明星姐弟自助远行真人秀节目，节目共11期。第二季节目七位固定成员是毛阿敏、许晴、宁静、陈意涵、郑爽、井柏然、杨洋。该节目由“花少姐弟团”展开一场前往英国、土耳其、阿联酋的没有经纪人、不准带助理、每天生活费有限的限制下，在人生地不熟，甚至语言都根本不通的国度，完成一段异域的背包奇妙之旅。','4,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('花儿与少年3','1,4','12','1','吴梦知','江疏影/古力娜扎','./varietyshow/HUAERYUSHAONIAN3.jpg','《花儿与少年第三季》是湖南卫视推出的青春伙伴自助远行真人秀节目，共12期。第三季节目八位固定成员是江疏影、古力娜扎、赖雨濛、宋祖儿、杨祐宁、陈柏霖、张若昀、井柏然。节目以“青春伙伴”的形式远赴赤道以南，游经巴西、南非、澳大利亚、纳米比亚四国，开启了一场别开生面的洲际穿越之旅。','4,99');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('挑战吧！太空','1,5','12','1','云天','王宝强/田亮/张雨绮','./recommend/TIAOZHANBATAIKONG1.jpg','《挑战吧！太空》节目由王宝强、张雨绮、田亮、吴宣仪、朱正廷、陈锴杰六位嘉宾作为“太空C计划”志愿者参与了节目拍摄，体验中国航天员训练体系，并前往火星模拟真实环境进行封闭式生存挑战。','2,4,99');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('王牌对王牌1','6','11','1','李牧鹏','王祖蓝/白百合/谢娜','./varietyshow/WANGPAIDUIWANGPAI1.jpg,./varietyshow/WANGPAIDUIWANGPAIDAHAIBAO.jpg','王牌对王牌第一季》是浙江卫视推出的大型原创室内竞技真人秀节目，由浙江卫视节目中心制作。节目每期围绕一个主题，邀请两支王牌团队，由两队固定队长各带领多名热门IP嘉宾进行PK对战，通过才艺比拼、游戏竞技，决出王牌中的王牌。','0,2');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('笑傲江湖1','6','12','1','朱慧','刘仪伟/宋丹丹/吴君如/冯小刚','./varietyshow/XIAOAOJIANGHU1.jpg','《笑傲江湖》是东方卫视举办的喜剧选秀节目。节目于2014年3月16日起，每周日晚9点在东方卫视播出。','2,4,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('笑傲江湖2','6','14','1','朱慧','冯小刚/宋丹丹/郭德纲','./varietyshow/XIAOAOJIANGHU2.jpg','笑傲江湖第二季》由冯小刚、郭德纲、宋丹丹三位担任评委。节目鼓励任何参赛者原创的节目形式，包括相声、小品、脱口秀还是唱歌、舞蹈、无厘头。','3,99');
insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('笑傲江湖3','6','13','1','朱慧','冯小刚/宋丹丹/郭德纲','./varietyshow/XIAOAOJIANGHU3.jpg','《笑傲江湖第三季》是东方卫视一档大型原创喜剧真人秀节目。由冯小刚、郭德纲、宋丹丹组成的“刚纲丹”观察员组合也再度为观众选出素人喜剧演员。','3,99');

insert into VarietyShow(name,type,episodes,region,director,actor,post,introduction,recommend) values('金星秀2017','7','33','1','金星','金星','./varietyshow/JINXINGXIU2017.jpg,./varietyshow/JINXINGXIUDAHAIBAO.jpg','优酷全网独播的《金星秀》是一档全新的大型时尚文化脱口秀节目。由著名舞蹈家金星独挑大梁，细数文娱热点话题，并进行麻辣点评。','0,4');